# Generated by Django 5.2.11 on 2026-02-09 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SotishRejasiYil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Sotish rejasi yili',
                'verbose_name_plural': 'Sotish rejasi yillari',
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='SotishMahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('unit', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('sotish_rejasi_yil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='smetalar.sotishrejasiyil')),
            ],
            options={
                'verbose_name': 'Sotish mahsuloti',
                'verbose_name_plural': 'Sotish mahsulotlari',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='XarajatlarSmetasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('completed', 'Yakunlangan')], db_index=True, default='draft', max_length=20)),
                ('project_name', models.CharField(max_length=300)),
                ('organization_name', models.CharField(blank=True, max_length=300)),
                ('project_description', models.TextField(blank=True)),
                ('project_duration_years', models.PositiveSmallIntegerField(default=2)),
                ('excel_file', models.FileField(blank=True, upload_to='smetalar/excel/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smetalar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Xarajatlar Smetasi',
                'verbose_name_plural': 'Xarajatlar Smetalari',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='sotishrejasiyil',
            name='smeta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sotish_rejasi_yillari', to='smetalar.xarajatlarsmetasi'),
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('unit', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('financing_source', models.CharField(choices=[('vazirlik', 'Vazirlik'), ('tashkilot', 'Tashkilot')], default='vazirlik', max_length=20)),
                ('smeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_materials', to='smetalar.xarajatlarsmetasi')),
            ],
            options={
                'verbose_name': 'Xom ashyo',
                'verbose_name_plural': 'Xom ashyolar',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('smeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='smetalar.xarajatlarsmetasi')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OtherExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('management', "Ma'muriy"), ('production', 'Ishlab chiqarish')], max_length=20)),
                ('name', models.CharField(max_length=500)),
                ('unit', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('financing_source', models.CharField(choices=[('vazirlik', 'Vazirlik'), ('tashkilot', 'Tashkilot')], default='vazirlik', max_length=20)),
                ('smeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_expenses', to='smetalar.xarajatlarsmetasi')),
            ],
            options={
                'verbose_name': 'Boshqa xarajat',
                'verbose_name_plural': 'Boshqa xarajatlar',
                'ordering': ['expense_type', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('link', models.URLField(blank=True, max_length=1000)),
                ('unit', models.CharField(default='dona', max_length=50)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('financing_source', models.CharField(choices=[('vazirlik', 'Vazirlik'), ('tashkilot', 'Tashkilot')], default='vazirlik', max_length=20)),
                ('smeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='smetalar.xarajatlarsmetasi')),
            ],
            options={
                'verbose_name': 'Inventar',
                'verbose_name_plural': 'Inventarlar',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_type', models.CharField(choices=[('management', "Ma'muriy-boshqaruv"), ('production', 'Ishlab chiqarish')], max_length=20)),
                ('position', models.CharField(max_length=300)),
                ('count', models.PositiveIntegerField(default=1)),
                ('monthly_salary', models.DecimalField(decimal_places=2, max_digits=15)),
                ('duration_months', models.PositiveSmallIntegerField(default=10)),
                ('financing_source', models.CharField(choices=[('vazirlik', 'Vazirlik'), ('tashkilot', 'Tashkilot')], default='vazirlik', max_length=20)),
                ('smeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='smetalar.xarajatlarsmetasi')),
            ],
            options={
                'verbose_name': 'Xodim',
                'verbose_name_plural': 'Xodimlar',
                'ordering': ['staff_type', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DavrXarajat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('smeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='davr_xarajatlari', to='smetalar.xarajatlarsmetasi')),
            ],
            options={
                'verbose_name': 'Davr xarajati',
                'verbose_name_plural': 'Davr xarajatlari',
                'ordering': ['id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='sotishrejasiyil',
            unique_together={('smeta', 'year')},
        ),
    ]
